"""Add original_sections to tailored_cvs

Revision ID: 0ed843c6f52b
Revises: a1b2c3d4e5f6
Create Date: 2026-06-21 17:57:07.057077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed843c6f52b'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tailored_cvs', sa.Column('original_sections', sa.JSON(), nullable=True))
    op.add_column('tailored_cvs', sa.Column('preview_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tailored_cvs', 'preview_summary')
    op.drop_column('tailored_cvs', 'original_sections')
    # ### end Alembic commands ###
