"""initial

Revision ID: 7e57014f7569
Revises: None
Create Date: 2026-06-19 20:37:52.101620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e57014f7569'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cv_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=False),
    sa.Column('embedding_index_path', sa.String(length=500), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_search_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('cv_profile_id', sa.Uuid(), nullable=True),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cv_profile_id'], ['cv_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_postings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('structured_requirements', sa.JSON(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['job_search_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('quick_wins', sa.JSON(), nullable=True),
    sa.Column('stretch_goals', sa.JSON(), nullable=True),
    sa.Column('develop_first', sa.JSON(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('week_1_actions', sa.JSON(), nullable=True),
    sa.Column('week_2_actions', sa.JSON(), nullable=True),
    sa.Column('skills_to_upskill', sa.JSON(), nullable=True),
    sa.Column('top_recommendation', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['job_search_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('fit_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('job_posting_id', sa.Uuid(), nullable=False),
    sa.Column('fit_percentage', sa.Integer(), nullable=False),
    sa.Column('fit_category', sa.String(length=50), nullable=False),
    sa.Column('skill_breakdown', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=True),
    sa.Column('transferable_skills', sa.JSON(), nullable=True),
    sa.Column('overall_reasoning', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['job_search_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tailored_cvs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_posting_id', sa.Uuid(), nullable=False),
    sa.Column('original_cv_id', sa.Uuid(), nullable=False),
    sa.Column('adapted_sections', sa.JSON(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=False),
    sa.Column('ats_score_estimate', sa.Integer(), nullable=True),
    sa.Column('approved_changes', sa.JSON(), nullable=True),
    sa.Column('pending_approval', sa.Boolean(), nullable=False),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_cv_id'], ['cv_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tailored_cvs')
    op.drop_table('fit_analyses')
    op.drop_table('strategies')
    op.drop_table('job_postings')
    op.drop_table('job_search_sessions')
    op.drop_table('cv_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
